/* empty css                      */import{S as g,N as p,E as v}from"./assets/vendor-DvTbVb7G.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();let c=null;document.addEventListener("DOMContentLoaded",()=>{window.innerWidth<1439||(c=new g(".about-swiper",{modules:[p,v],effect:"cards",grabCursor:!0,loop:!1,cardsEffect:{perSlideOffset:12,perSlideRotate:0,slideShadows:!1},navigation:{nextEl:".custom-next"},on:{init(){y(),u()},slideChange(){u()}}}))});function y(){const i=document.querySelectorAll(".pagination-item");c&&i.forEach((o,s)=>{o.addEventListener("click",()=>{c.slideTo(s)})})}function u(){if(!c)return;const i=document.querySelectorAll(".pagination-item"),o=c.activeIndex;i.forEach((s,n)=>{s.classList.toggle("active",n===o)})}document.querySelectorAll(".faq-acc-el-trigger").forEach(i=>{i.addEventListener("click",()=>{const o=i.closest(".faq-acc-el"),s=o.querySelector(".faq-acc-el-descr-frame"),n=o.querySelector(".faq-img");o.classList.contains("open")?(o.classList.remove("open"),n==null||n.classList.remove("rotated"),s&&(s.style.maxHeight="0")):(o.classList.add("open"),n==null||n.classList.add("rotated"),s&&(s.style.maxHeight=s.scrollHeight+"px"))})});document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),o=i.querySelector(".icon"),s=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const r=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 6H21V8H3V6ZM3 11H21V13H3V11ZM3 16H21V18H3V16Z" fill="white" />
</svg>
    `,l=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 6H21V8H3V6ZM3 11H21V13H3V11ZM3 16H21V18H3V16Z" fill="white" />
</svg>
    `;i.addEventListener("click",()=>{t=!t,o.innerHTML=t?l:r,t?a():d()}),n.forEach(h=>h.addEventListener("click",()=>{d(),o.innerHTML=r,t=!1})),window.addEventListener("scroll",m);function a(){s.style.display="block"}function d(){s.style.display="none"}function m(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const e=document.getElementById(n);if(!e)return;const t=i(),r=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll('a[href*="#"]').forEach(n=>{n.addEventListener("click",e=>{const t=n.getAttribute("href");if(t.startsWith("http")||!t.startsWith("#")&&!t.includes("index.html#"))return;e.preventDefault();const l=t.indexOf("#"),a=t.substring(l+1);o(a)})});const s=window.location.hash;if(s){const n=s.substring(1);setTimeout(()=>{o(n)},500)}});const f=document.querySelectorAll(".navigation-item");f.forEach(i=>{i.addEventListener("click",function(o){o.preventDefault(),f.forEach(s=>s.classList.remove("active")),this.classList.add("active")})});
//# sourceMappingURL=index.js.map
